"""phase1: identity, profile, couple, conversation

Revision ID: 5ae9ed8bc2fc
Revises: 
Create Date: 2026-07-28 16:30:26.986481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae9ed8bc2fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apple_sub', sa.String(length=255), nullable=False),
    sa.Column('email_relay', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_sub'), 'users', ['apple_sub'], unique=True)
    op.create_table('app_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_app_sessions_user_id'), 'app_sessions', ['user_id'], unique=False)
    op.create_table('apple_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('tos', 'privacy', 'ai_disclosure', 'relay_sharing', name='consent_kind'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('wording_hash', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('couples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'dissolved', name='couple_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dissolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolved_by', sa.UUID(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dissolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by', sa.UUID(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code_hash'), 'invites', ['code_hash'], unique=False)
    op.create_index(op.f('ix_invites_created_by'), 'invites', ['created_by'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('pronouns', sa.Enum('he_him', 'she_her', 'they_them', 'not_stated', name='pronouns'), nullable=False),
    sa.Column('relationship_status', sa.Enum('married', 'partners', 'dating', 'separated', 'other', 'not_stated', name='relationship_status'), nullable=False),
    sa.Column('together_months', sa.Integer(), nullable=True),
    sa.Column('pacing_preference', sa.Enum('needs_time', 'right_away', 'depends', 'not_stated', name='pacing_preference'), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('apns_token', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'apns_token', name='uq_push_user_token')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('couple_members',
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('couple_id', 'user_id')
    )
    op.create_index('uq_one_active_couple', 'couple_members', ['user_id'], unique=True, postgresql_where=sa.text('left_at IS NULL'))
    op.create_table('mediation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('intro', 'private', 'relay_delivery', name='session_kind'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediation_sessions_owner_user_id'), 'mediation_sessions', ['owner_user_id'], unique=False)
    op.create_table('pairing_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('invitee_user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'accepted', 'declined', 'expired', 'revoked', name='invite_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_requests_invite_id'), 'pairing_requests', ['invite_id'], unique=False)
    op.create_index(op.f('ix_pairing_requests_invitee_user_id'), 'pairing_requests', ['invitee_user_id'], unique=False)
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['mediation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_expires_at'), 'audio_assets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_audio_assets_owner_user_id'), 'audio_assets', ['owner_user_id'], unique=False)
    op.create_table('relays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('draft_json_enc', sa.Text(), nullable=True),
    sa.Column('approved_text_enc', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'approved', 'scheduled', 'delivered', 'withdrawn', name='relay_state'), nullable=False),
    sa.Column('perspective_warning', sa.Boolean(), nullable=False),
    sa.Column('abuse_flag', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliver_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_id', sa.String(length=64), nullable=True),
    sa.Column('author_tombstoned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['mediation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relays_couple_id'), 'relays', ['couple_id'], unique=False)
    op.create_index(op.f('ix_relays_from_user_id'), 'relays', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_relays_state'), 'relays', ['state'], unique=False)
    op.create_index(op.f('ix_relays_to_user_id'), 'relays', ['to_user_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mediation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='turn_role'), nullable=False),
    sa.Column('text_enc', sa.Text(), nullable=False),
    sa.Column('audio_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mediation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_relays_to_user_id'), table_name='relays')
    op.drop_index(op.f('ix_relays_state'), table_name='relays')
    op.drop_index(op.f('ix_relays_from_user_id'), table_name='relays')
    op.drop_index(op.f('ix_relays_couple_id'), table_name='relays')
    op.drop_table('relays')
    op.drop_index(op.f('ix_audio_assets_owner_user_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_expires_at'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index(op.f('ix_pairing_requests_invitee_user_id'), table_name='pairing_requests')
    op.drop_index(op.f('ix_pairing_requests_invite_id'), table_name='pairing_requests')
    op.drop_table('pairing_requests')
    op.drop_index(op.f('ix_mediation_sessions_owner_user_id'), table_name='mediation_sessions')
    op.drop_table('mediation_sessions')
    op.drop_index('uq_one_active_couple', table_name='couple_members', postgresql_where=sa.text('left_at IS NULL'))
    op.drop_table('couple_members')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_invites_created_by'), table_name='invites')
    op.drop_index(op.f('ix_invites_code_hash'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('couples')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('apple_credentials')
    op.drop_index(op.f('ix_app_sessions_user_id'), table_name='app_sessions')
    op.drop_table('app_sessions')
    op.drop_index(op.f('ix_users_apple_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
